"""Pipeline and scoring constants."""

# Correction thresholds
REPLACE_THRESHOLD = 0.85
MIN_MARGIN = 0.20
AMBIGUOUS_MARGIN = 0.10

# Candidate generation
MAX_CANDIDATES_PER_TOKEN = 8
MAX_TOKENS_PER_WINDOW = 7
MAX_COMBINATIONS_PER_WINDOW = 5000

# Scoring weights
WORD_VALIDITY_WEIGHT = 1.0
SYLLABLE_FREQUENCY_WEIGHT = 0.8
PHRASE_NGRAM_WEIGHT = 2.5
DOMAIN_CONTEXT_WEIGHT = 3.0
OCR_CONFUSION_WEIGHT = 1.5
EDIT_DISTANCE_WEIGHT = 0.5
OVERCORRECTION_PENALTY = 2.0

# Production targets
TARGET_CORRECTION_PRECISION = 0.95
TARGET_PROTECTED_VIOLATION_RATE = 0.0
TARGET_OVERCORRECTION_RATE = 0.01

# Unicode
UNICODE_NORMALIZATION_FORM = "NFC"
